name: CI

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

env:
  NODE_VERSION: 12.x

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
      - name: Lint
        run: yarn lint
        env:
          CI: true
      - name: test change
        run: echo "Hello World"
      - name: Build
        run: yarn build
        env:
          CI: true
